CREATE TABLE IF NOT EXISTS alertas_preferencias (
    id TINYINT UNSIGNED NOT NULL PRIMARY KEY,
    dados JSON NOT NULL,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
