-- NyxCloud - autenticação inicial

CREATE TABLE IF NOT EXISTS schema_migrations (
    version VARCHAR(255) PRIMARY KEY,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    email VARCHAR(255) NOT NULL,
    senha_hash VARCHAR(255) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    ultimo_login_em TIMESTAMPTZ,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_usuario_email_lower
    ON usuario (LOWER(email));

-- Credencial inicial: admin@nyxcloud.com.br / admin
INSERT INTO usuario (nome, email, senha_hash)
VALUES (
    'Administrador',
    'admin@nyxcloud.com.br',
    '$2y$12$ebEFYpe8R/DEQgFoOKn1M.RU2lPmtabLFV8RqHqjQ07O9xYuU5y1S'
)
ON CONFLICT DO NOTHING;

