-- NyxCloud - auditoria de contas

CREATE TABLE IF NOT EXISTS usuario_auditoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ator_id BIGINT REFERENCES usuario(id) ON DELETE SET NULL,
    alvo_usuario_id BIGINT REFERENCES usuario(id) ON DELETE SET NULL,
    acao VARCHAR(80) NOT NULL,
    detalhes JSONB NOT NULL DEFAULT '{}'::jsonb,
    ip VARCHAR(64),
    user_agent VARCHAR(500),
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_usuario_auditoria_criado_em
    ON usuario_auditoria (criado_em DESC);

CREATE INDEX IF NOT EXISTS ix_usuario_auditoria_ator
    ON usuario_auditoria (ator_id);

CREATE INDEX IF NOT EXISTS ix_usuario_auditoria_alvo
    ON usuario_auditoria (alvo_usuario_id);
