CREATE TABLE IF NOT EXISTS acronis_cliente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id BIGINT NOT NULL REFERENCES empresa(id) ON DELETE RESTRICT,
    conta_acronis_id VARCHAR(191) NOT NULL,
    tenant_acronis_id VARCHAR(191) NOT NULL,
    nome VARCHAR(255) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ux_acronis_cliente_tenant UNIQUE (conta_acronis_id, tenant_acronis_id)
);

CREATE INDEX IF NOT EXISTS ix_acronis_cliente_empresa_ativo ON acronis_cliente (empresa_id, ativo);
