CREATE TABLE IF NOT EXISTS alertas_email_configuracao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    escopo VARCHAR(20) NOT NULL CHECK (escopo IN ('global', 'empresa')),
    empresa_id BIGINT NULL REFERENCES empresa(id) ON DELETE CASCADE,
    escopo_chave VARCHAR(100) NOT NULL UNIQUE,
    ativo BOOLEAN NOT NULL DEFAULT FALSE,
    modo VARCHAR(20) NOT NULL DEFAULT 'actionable' CHECK (modo IN ('all', 'actionable')),
    frequencia VARCHAR(20) NOT NULL DEFAULT 'instant' CHECK (frequencia IN ('instant', 'hourly', 'daily')),
    criado_por BIGINT NULL REFERENCES usuario(id) ON DELETE SET NULL,
    atualizado_por BIGINT NULL REFERENCES usuario(id) ON DELETE SET NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_alertas_email_config_empresa
    ON alertas_email_configuracao (empresa_id);

CREATE TABLE IF NOT EXISTS alertas_email_destinatario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    configuracao_id BIGINT NOT NULL REFERENCES alertas_email_configuracao(id) ON DELETE CASCADE,
    usuario_id BIGINT NULL REFERENCES usuario(id) ON DELETE CASCADE,
    email VARCHAR(254) NULL,
    nome VARCHAR(180) NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_alertas_email_destinatario_alvo CHECK ((usuario_id IS NOT NULL AND email IS NULL) OR (usuario_id IS NULL AND email IS NOT NULL))
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_alertas_email_dest_usuario
    ON alertas_email_destinatario (configuracao_id, usuario_id)
    WHERE usuario_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_alertas_email_dest_email
    ON alertas_email_destinatario (configuracao_id, email)
    WHERE email IS NOT NULL;
